---
env:
  TF_VAR_build_cicd: true

name: "Terraform Apply"
on:
  workflow_call:
    inputs:
      provider:
        description: 'Specifies the cloud provider.'
        required: true
        type: string
      path:
        description: 'Specifies the path of the root terraform module.'
        required: true
        type: string
      tf_version:
        description: 'Specifies version of Terraform to use. e.g: 1.1.0 Default=latest.'
        required: false
        type: string
        default: latest
      gh_environment:
        description: 'Specifies the GitHub deployment environment.'
        required: false
        type: string
        # default: null
      infra_type:
        description: 'Specifies the type of deployment. Used for plan title.'
        required: true
        type: string
      build_path:
        description: 'Specifies the path of the build artifact.'
        required: false
        type: string
      build_artifact:
        description: 'Specifies the name of the build artifact.'
        required: false
        type: string
      build_artifact_uuid:
        description: 'Specifies the UUID of the build artifact.'
        required: false
        type: string

jobs:
  apply:
    name: apply-${{ inputs.gh_environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.gh_environment }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.path }}
    env:
      TF_LOG: TRACE
      TF_LOG_PATH: tf.log
      TF_IN_AUTOMATION: true
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_build_cicd: true
      PLAN_TITLE: "${{ inputs.infra_type }} Infra"
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Download Terraform Artifact
        env:
          THIS_REPO: ${{ github.repository }}
        if: inputs.gh_environment != 'uat'
        uses: actions/download-artifact@v3.0.2
        with:
          name: "${{ inputs.gh_environment }}"
          path: ${{ inputs.path }}

      # can't be any ambiguity in the name of the artifact or workflow
      # a duplicate name will cause the download to fail
      # if you create a new workflow with the same name (but diff file?), you'll need to delete the old one (and all runs)
      - name: Download Terraform Artifact - UAT
        if: inputs.gh_environment == 'uat'
        run: |
          REPO="$THIS_REPO"
          WF_NAME="$PLAN_TITLE"
          BRANCH='uat'
          ARTIFACT_NAME="$BRANCH"
          RUN_ID=$(gh run --repo "${REPO}" list --workflow "${WF_NAME}" --branch "${BRANCH}" --json databaseId --jq '.[0].databaseId')
          gh run --repo "${REPO}" download "${RUN_ID}" -n "${ARTIFACT_NAME}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Decompress TF Plan artifact
        run: |
          rm .terraform.lock.hcl
          unzip "${{ inputs.gh_environment }}".zip

      - name: Download Build Artifact
        if: inputs.build_path != '' && inputs.gh_environment != 'uat'
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.build_artifact_uuid }}
          path: ${{ inputs.build_path }}

      - name: Download Build Artifact - UAT
        if: inputs.build_path != '' && inputs.gh_environment == 'uat'
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.build_artifact_uuid }}
          path: ${{ inputs.build_path }}

      - name: Decompress Build artifact
        if: inputs.build_path != ''
        working-directory: ${{ inputs.build_path }}
        run: |
          unzip "${{ inputs.build_artifact }}".zip
          rm "${{ inputs.build_artifact }}".zip

      - name: AWS Credentials
        # uses: ./.github/actions/aws-creds
        # uses: shortpoet/tf-web/.github/actions/aws-creds@main
        uses: shortpoet/.github/.github/actions/aws-creds@main
        if: inputs.provider == 'aws'
        with:
          aws-profile: ${{ vars.AWS_PROFILE }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 1200

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Terraform Apply
        run: terraform apply plan.tfplan
